language: java
jdk:
  - oraclejdk8

before_install:
 - chmod +x gradlew

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_deploy:
  - sudo apt-get update -qq
  - sudo apt-get install -qq expect rsync
  - ./gradlew :errorcant-web:buildNeeded
  - ./gradlew :errorcant-api:buildNeeded
  - chmod +x deploy.sh

deploy:
  skip_cleanup: true
  provider: script
  script: "./deploy.sh"
