spring:
  data:
    mongodb:
      database: errorcant-dev
      host: localhost
  thymeleaf:
    cache: false
logging:
  level:
    root: DEBUG
server:
  port: 2677
github:
  client:
    clientId: ${ERRORCANT_GITHUB_CLIENTID}
    clientSecret: ${ERRORCANT_GITHUB_CLIENTSECRET}
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user
security:
  user:
    name: spring
    password: spring
  oauth2:
    client:
      clientId: ${ERRORCANT_GITHUB_CLIENTID}
      clientSecret: ${ERRORCANT_GITHUB_CLIENTSECRET}
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user
---
spring:
  profiles: production
  data:
    mongodb:
      database: errorcant-prd
      host: localhost

logging:
  level:
    root: INFO